// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetFamily.Infrastructure.Data;

#nullable disable

namespace PetFamily.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetFamily.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONSULTA");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PET_ID");

                    b.HasKey("Id");

                    b.HasIndex("DataConsulta")
                        .HasDatabaseName("IX_CONSULTAS_DATA");

                    b.HasIndex("PetId")
                        .HasDatabaseName("IX_CONSULTAS_PET_ID");

                    b.ToTable("CONSULTAS", (string)null);
                });

            modelBuilder.Entity("PetFamily.Domain.Entities.Lembrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLembrete")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEMBRETE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PET_ID");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("DataLembrete")
                        .HasDatabaseName("IX_LEMBRETES_DATA");

                    b.HasIndex("PetId")
                        .HasDatabaseName("IX_LEMBRETES_PET_ID");

                    b.ToTable("LEMBRETES", (string)null);
                });

            modelBuilder.Entity("PetFamily.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RACA");

                    b.Property<int>("TutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TUTOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("Especie")
                        .HasDatabaseName("IX_PETS_ESPECIE");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("IX_PETS_TUTOR_ID");

                    b.ToTable("PETS", (string)null);
                });

            modelBuilder.Entity("PetFamily.Domain.Entities.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_TUTORES_EMAIL");

                    b.ToTable("TUTORES", (string)null);
                });

            modelBuilder.Entity("PetFamily.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("PetFamily.Domain.Entities.Pet", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetFamily.Domain.Entities.Lembrete", b =>
                {
                    b.HasOne("PetFamily.Domain.Entities.Pet", "Pet")
                        .WithMany("Lembretes")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetFamily.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetFamily.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PetFamily.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Lembretes");
                });

            modelBuilder.Entity("PetFamily.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
